# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d3e526b968ee1b47c5d3e9b8dcf5a9d706577682203931ee99598ebca4085292564b1cab2eae6e9d46d48c7e1f98db5700acdb36d8eed970aa5def482845f23

test:
  secret_key_base: f2f00ff6bc24a2d2ad29a35b713069a62500216babdca95d6fd57cacdc1220cee618a4a319f765148cfef2fad30b93e6bbc97232c8671671855d9b229405d107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
